### ISSUE TITLE
500 Error with finding VERSION file inside container image while scanning

### ISSUE THREAD

**Issue by agu3rra** [blackducksoftware/hub-docker#26]
## docker-inspector version
9.2.3

## Scan command
> java -jar blackduck-docker-inspector-9.2.3.jar --blackduck.url=https://[REDACTED].blackducksoftware.com --blackduck.api.token=${TOKEN} --blackduck.project.name=[SOMENAME] blackduck.project.version=[SOMEVERSION] --docker.image=[IMAGE]:[TAG]

## Error
> 2021-08-16 08:43:30.990 ERROR 39984 --- [           main] c.s.i.b.dockerinspector.DockerInspector  : Error inspecting image: There was a problem trying to getBdio. Error: 500; Warning header: 'Error inspecting image: /tmp/ImageInspectorApi_http-nio-8082-exec-5_[REDACTED].tar/[REDACTED]/VERSION (No such file or directory)'; Body: 'Exception thrown while getting image packages: Error inspecting image: /tmp/ImageInspectorApi_http-nio-8082-exec-5_[REDACTED].tar/[REDACTED]/VERSION (No such file or directory)'

## Expectation
The image was in the docker cache as it was pulled locally. Is there any specific expectation on how the image to be scanned is supposed to be generated? Is `docker-inspector` looking for a specific VERSION file in any of its scans and if so, can I disable that part?

**Comment by stevebillings** [comment]
@agu3rra  Please contact Synopsys technical support for all support-related issues: https://community.synopsys.com/
